### ISSUE TITLE
"Failed to generate PFX file for Certificate."

### ISSUE THREAD

**Issue by shemsargent-rvtd** [webprofusion/certify#12]
Context: Windows Server 2012 R2, IIS 8.5
Never used Let's Encrypt on this server before.

I ran through a couple of aborted attempts to use Certify to install a Let's Encrypt certificate. I resolved file permission and IIS redirect issues for the .well-known\acme-challenge folder and http firewall port.

I now get a message during certificate request:
"Failed to generate PFX file for Certificate."

Any suggestions on how to address this would be appreciated.

Thank you,
Shem

The log follows:
[12:00 PM] Powershell: New-ACMEIdentifier -Dns [domain] -Alias [domain]_7e20b4 -Label Identifier:[domain]
[12:00 PM] Powershell: Complete-ACMEChallenge -Ref [domain]_7e20b4 -ChallengeType http-01 -Handler manual  -Regenerate
[12:00 PM] Powershell: Submit-ACMEChallenge -Ref [domain]_7e20b4 -Challenge http-01
[12:00 PM] Powershell: Update-ACMEIdentifier -Ref [domain]_7e20b4
[12:00 PM] Powershell: Update-ACMEIdentifier -Ref [domain]_7e20b4
[12:00 PM] Powershell: New-ACMECertificate -Identifier [domain]_7e20b4 -Alias cert_[domain]_7e20b4 -Generate
[12:00 PM] Powershell: Update-ACMEIdentifier -Ref [domain]_7e20b4
[12:00 PM] Powershell: Update-ACMEIdentifier -Ref [domain]_7e20b4
[12:00 PM] Powershell: Get-ACMECertificate -Ref =[GUID] -ExportPkcs12 C:\ProgramData\ACMESharp\sysVault\99-ASSET[GUID]-all.pfx -Overwrite
[12:00 PM] [Error]: System.Management.Automation.CmdletInvocationException: Cannot export PKCS12; private hasn't been imported or generated ---> System.InvalidOperationException: Cannot export PKCS12; private hasn't been imported or generated
   at ACMESharp.POSH.GetCertificate.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.InvokeCurrentPSCommand()

**Comment by webprofusion-chrisc** [comment]
Hi, looks like the original failed attempt left it in an inconsistent state. If you can now freely browse over http to the extensionless checkconfig file under /.well-known/... from your web browser then try deleting the attempt and starting again. Right click on the domain in the tree view, choose delete, then request the certificate again.

**Comment by oising** [comment]
Same issue. Tried leaving .well-known and deleting attempt from the tool, no luck. Tried deleting well-known and attempt, still doesn't work. Same error. On server 2012.

**Comment by shemsargent-rvtd** [comment]
Chris,

Thank you for working on this free software for me and others. I appreciate your response and good suggestion. I tested all the permutations I could think of using your suggestion (apparently the same as Oising above) and still receive the same message and log output. I can reach the checkconfig file from outside our network via http. I deleted the content of acme-challenge folder. I removed all the Vault/Domains and Certificates entries from Certify. I also tried permutations Including Reload Vault and Cleanup Vault menu options. I then renamed the C:\ProgramData\ACMESharp\sysVault folder and restarted Certify and tried everything from scratch using the same contact email address. Each time, Certify gave the same PFX error. I'm hoping you might have another suggestion.

Thank you,
Shem

**Comment by webprofusion-chrisc** [comment]
I'm currently at a loss on this one as you've tried everything I would have done, including starting a new Vault. I'm also using 2012 (R2) and it's currently working for me (not helpful, I know).

I don't think this issue is to do with extensionless files etc as the app attempts it's own check over http which would warn you if there was a problem.

You could try running the ACMESharp powershell commands yourself, but I know that's a hassle - it might give you more detail. I'm low on free time at the moment which makes it difficult for me to investigate fully.

**Comment by matthewproctor** [comment]
I used the powershell command, and found it responded with "too many certs" (I'd been experimenting all day and exceeded the 20-cert limit per day per domain).   :+1:  [https://letsencrypt.org/docs/rate-limits/](https://letsencrypt.org/docs/rate-limits/)

**Comment by soundshed** [comment]
Closing.
