### ISSUE TITLE
asset file does not exist System.IO.FileNotFoundException: asset file does not exist

### ISSUE THREAD

**Issue by charlie063** [webprofusion/certify#192]
2017-10-25 15:36:48.572 +02:00 [Information] Beginning Certificate Request Process: Default Web Site
2017-10-25 15:36:48.774 +02:00 [Information] Attempting Domain Validation: sub1.domain.gtld
2017-10-25 15:36:50.181 +02:00 [Information] Domain already has current authorization, skipping verification: sub1.domain.gtld
2017-10-25 15:36:50.182 +02:00 [Information] Attempting Domain Validation: sub1.domain2.gtld
2017-10-25 15:36:51.497 +02:00 [Information] Domain already has current authorization, skipping verification: sub1.domain2.gtld
2017-10-25 15:37:06.586 +02:00 [Information] Requesting Certificate via Lets Encrypt
2017-10-25 15:37:21.317 +02:00 [Information] Default Web Site: Request failed - asset file does not exist System.IO.FileNotFoundException: asset file does not exist
   at ACMESharp.Vault.Providers.LocalDiskVault.GetAsset(VaultAssetType type, String name)
   at Certify.ACMESharpCompat.ACMESharpUtils.GetCertificate(String certRef, String ExportKeyPEM, String ExportCsrPEM, String ExportCertificatePEM, String ExportCertificateDER, String ExportIssuerPEM, String ExportIssuerDER, String ExportPkcs12, String CertificatePassword, String PkiTool, Boolean overwrite, String vaultProfile)
   at Certify.VaultManager.ExportCertificate(String certRef, Boolean pfxOnly)
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs)
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers)
   at Certify.Management.CertifyManager.<>c__DisplayClass34_0.<<PerformCertificateRequest>b__0>d.MoveNext()

What is the issue? and how do I solve this?
Thanks!

**Comment by Marcus-L** [comment]
Please describe what you were trying to do (first time cert request? renewal? command line renewal?), the version of the app you are using (latest v2.1.20?), version of Windows (10? Server 2012r2?), it will help debug, thanks!

**Comment by charlie063** [comment]
W2012 R2 adding certificates to a different domain  yes it is the latest version downloaded. If I can be of any help? please feel free to contact me

**Comment by webprofusion-chrisc** [comment]
@charlie063  can you try renaming or deleting your c:\programdata\acmesharp\sysvault folder and running the app again. I'm not sure that's the problem but it's an unusual error and sounds similar to when there is a problem decrypting encrypted storage. Always use the same account to run the app as well as for Auto Renew.

**Comment by charlie063** [comment]
solved! in combination with the latest version d.d. 2017.10.26 many thanks! Keep up the good work!
