### ISSUE TITLE
When a large list of manage sites are saved can result in OutOfMemory exception

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#193]
An error occurred: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Certify.Management.ItemManager.StoreSettings()
   at Certify.UI.ViewModel.AppModel.AddOrUpdateManagedSite(ManagedSite item)
   at Certify.UI.ViewModel.AppModel.SaveManagedItemChanges()

**Comment by webprofusion-chrisc** [comment]
Load/save now uses streamed json token read/write instead of reading all text.
