### ISSUE TITLE
Request failed - A specified logon session does not exist

### ISSUE THREAD

**Issue by GeoSheehy** [webprofusion/certify#222]
I am getting this from one of my sites. Other sites are working fine.
----
2017-12-01 21:54:44.076 -05:00 [Information] Beginning Certificate Request Process: AnsoniaFoodServices
2017-12-01 21:54:44.286 -05:00 [Information] Attempting Domain Validation: www.ansoniafoodservices.com
2017-12-01 21:54:50.842 -05:00 [Information] Domain validation completed: www.ansoniafoodservices.com
2017-12-01 21:54:50.843 -05:00 [Information] Requesting Certificate via Lets Encrypt
2017-12-01 21:54:56.841 -05:00 [Information] Completed Certificate Request.
2017-12-01 21:54:57.062 -05:00 [Information] AnsoniaFoodServices: Request failed - A specified logon session does not exist. It may already have been terminated System.ComponentModel.Win32Exception (0x80004005): A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, Byte[] certificateHash, String certificateStoreName, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Certify.Management.IISManager.InstallCertificateforBinding(Site site, X509Certificate2 certificate, String host, Int32 sslPort, Boolean useSNI, String ipAddress)
   at Certify.Management.IISManager.InstallCertForRequest(ManagedSite managedSite, String pfxPath, Boolean cleanupCertStore)
   at Certify.Management.CertifyManager.<>c__DisplayClass36_0.<<PerformCertificateRequest>b__0>d.MoveNext()

**Comment by webprofusion-chrisc** [comment]
Hi @GeoSheehy please upgrade to the v3 beta. We will do a patch for 2.x but v3 already has the fixed.

**Comment by GeoSheehy** [comment]
That worked - Thanks and thanks for the quick response!

**Comment by GeoSheehy** [comment]
I am getting this again, Version 3.0.9.36623
---
2018-01-05 09:23:28.681 -05:00 [INF] Performing Config Tests
2018-01-05 09:23:30.271 -05:00 [INF] Beginning Certificate Request Process: AnsoniaFoodServices
2018-01-05 09:23:30.272 -05:00 [INF] Registering Domain Identifiers
2018-01-05 09:23:30.272 -05:00 [INF] Attempting Domain Validation: www.ansoniafoodservices.com
2018-01-05 09:23:30.273 -05:00 [INF] Registering and Validating www.ansoniafoodservices.com 
2018-01-05 09:23:33.418 -05:00 [INF] Performing Challenge Response via IIS: www.ansoniafoodservices.com 
2018-01-05 09:23:34.051 -05:00 [INF] Requesting Validation from Let's Encrypt: www.ansoniafoodservices.com
2018-01-05 09:23:35.050 -05:00 [INF] Domain validation completed: www.ansoniafoodservices.com
2018-01-05 09:23:35.051 -05:00 [INF] Requesting Certificate via Lets Encrypt
2018-01-05 09:23:45.750 -05:00 [INF] Completed Certificate Request.
2018-01-05 09:23:45.824 -05:00 [INF] Performing Automated Certificate Binding
2018-01-05 09:23:46.996 -05:00 [INF] AnsoniaFoodServices: Request failed - A specified logon session does not exist. It may already have been terminated System.ComponentModel.Win32Exception (0x80004005): A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, Byte[] certificateHash, String certificateStoreName, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Certify.Management.IISManager.InstallCertificateforBinding(Site site, X509Certificate2 certificate, String host, Int32 sslPort, Boolean useSNI, String ipAddress, Boolean alwaysRecreateBindings) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 612
   at Certify.Management.IISManager.<InstallCertForRequest>d__27.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 466
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 716
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-01-05 09:23:46.997 -05:00 [INF] AnsoniaFoodServices: Request failed - A specified logon session does not exist. It may already have been terminated System.ComponentModel.Win32Exception (0x80004005): A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, Byte[] certificateHash, String certificateStoreName, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Certify.Management.IISManager.InstallCertificateforBinding(Site site, X509Certificate2 certificate, String host, Int32 sslPort, Boolean useSNI, String ipAddress, Boolean alwaysRecreateBindings) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 612
   at Certify.Management.IISManager.<InstallCertForRequest>d__27.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 466
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 716
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420

**Comment by webprofusion-chrisc** [comment]
Thanks, can you confirm if you Scheduled Task is enabled still? It can be disabled/removed from v3 onwards as the background service does all the work. Also can you confirm if you Scheduled Task was running an alternative user (like a service account?) and that your Certify.Service background service is running as the default (Local System).

The workaround for this binding issue is to use the 'Reapply certificate to bindings' button on the Info tab of your managed site.

**Comment by webprofusion-chrisc** [comment]
And can you also confirm you are not using any other tools on the same server/domain such as ACMESharp or Let's Encrypt Win Simple which could be conflicting.

**Comment by webprofusion-chrisc** [comment]
Btw, I am currently in discussions with Microsoft concerning issues related to bindings errors, so thanks for raising this.

**Comment by GeoSheehy** [comment]
I was using "Let's Encrypt Win Simple" I will look in to removing all references to it. Also, The Task Schedule is enable with the default account.

**Comment by GeoSheehy** [comment]
I've checked the Task scheduler and it seems ok. I've attached a screen shop of the task status,
Also, I disabled all task from "Let's Encrypt Win Simple".

![capture](https://user-images.githubusercontent.com/5929937/34727089-e4f0bf0e-f523-11e7-8f54-488069080311.PNG)

**Comment by GeoSheehy** [comment]
Just to try, I delete and re added the sites that I was getting this error on and it's working ok now.

**Comment by webprofusion-chrisc** [comment]
As of v3 the scheduled task is no longer required for Certify. You can delete the scheduled task or go into Configure Auto Renew and confirm the choice of 'Background service' to auto remove it.

**Comment by maxlego** [comment]
It seems that problem still exists with sites having multiple bindings (using version 3.0.11.30336).  
As a result first certificate is requested and registered to iis successfully but not bound to host name. Binding is removed instead.

**Comment by webprofusion-chrisc** [comment]
@maxlego can you clarify what problem you are seeing? We don't delete any https bindings but we do cleanup old certificates we think are no longer used. Does your site have multiple https bindings against the same domain (perhaps different ports?)

**Comment by kd8ssq** [comment]
I had the same problem today as @maxlego.  

I had previously used Lets Encrypt Simple to create a cert for a domain and received the same error.  I had to delete the old cert from IIS and restart the Certify service.  Once I did that, I attempted to re-bind the cert to the IIS bindings and the Certify program said it was successful, but it actually didn't bind the cert to the bindings.  I had to go into IIS and bind the cert manually.  I think it has something to do with the old cert association, but I'm not sure.

**Comment by kd8ssq** [comment]
Chris,
Here's my full log file for the domain in question.

`2018-03-21 11:25:31.377 -04:00 [INF] Performing Config Tests
2018-03-21 11:25:35.035 -04:00 [INF] Beginning Certificate Request Process: cbcdavison.org
2018-03-21 11:25:35.036 -04:00 [INF] Registering Domain Identifiers
2018-03-21 11:25:35.036 -04:00 [INF] Attempting Domain Validation: cbcdavison.org
2018-03-21 11:25:35.036 -04:00 [INF] Registering and Validating cbcdavison.org 
2018-03-21 11:25:40.557 -04:00 [INF] Performing Challenge Response via IIS: cbcdavison.org 
2018-03-21 11:25:41.575 -04:00 [INF] Requesting Validation from Let's Encrypt: cbcdavison.org
2018-03-21 11:25:42.954 -04:00 [INF] Domain validation completed: cbcdavison.org
2018-03-21 11:25:42.955 -04:00 [INF] Attempting Domain Validation: www.cbcdavison.org
2018-03-21 11:25:42.955 -04:00 [INF] Registering and Validating www.cbcdavison.org 
2018-03-21 11:25:44.248 -04:00 [INF] Performing Challenge Response via IIS: www.cbcdavison.org 
2018-03-21 11:25:45.264 -04:00 [INF] Requesting Validation from Let's Encrypt: www.cbcdavison.org
2018-03-21 11:25:46.375 -04:00 [INF] Domain validation completed: www.cbcdavison.org
2018-03-21 11:25:46.376 -04:00 [INF] Requesting Certificate via Lets Encrypt
2018-03-21 11:25:55.762 -04:00 [INF] Completed Certificate Request.
2018-03-21 11:25:55.978 -04:00 [INF] Performing Automated Certificate Binding
2018-03-21 11:25:57.443 -04:00 [INF] cbcdavison.org: Request failed - A specified logon session does not exist. It may already have been terminated System.ComponentModel.Win32Exception (0x80004005): A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, Byte[] certificateHash, String certificateStoreName, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Certify.Management.IISManager.InstallCertificateforBinding(String certStoreName, Byte[] certificateHash, Site site, String host, Int32 sslPort, Boolean useSNI, String ipAddress, Boolean alwaysRecreateBindings) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 644
   at Certify.Management.IISManager.<InstallCertForRequest>d__31.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 484
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 717
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-03-21 11:25:57.444 -04:00 [INF] cbcdavison.org: Request failed - A specified logon session does not exist. It may already have been terminated System.ComponentModel.Win32Exception (0x80004005): A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, Byte[] certificateHash, String certificateStoreName, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at Certify.Management.IISManager.InstallCertificateforBinding(String certStoreName, Byte[] certificateHash, Site site, String host, Int32 sslPort, Boolean useSNI, String ipAddress, Boolean alwaysRecreateBindings) in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 644
   at Certify.Management.IISManager.<InstallCertForRequest>d__31.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\IISManager.cs:line 484
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 717
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-03-21 11:30:40.029 -04:00 [INF] Performing Automated Certificate Binding
2018-03-21 11:33:34.974 -04:00 [INF] Performing Automated Certificate Binding
2018-03-21 11:33:36.424 -04:00 [INF] Completed certificate request and automated bindings update (IIS)
2018-03-21 11:33:37.485 -04:00 [INF] Certificate installed and SSL bindings updated for cbcdavison.org
`

**Comment by webprofusion-chrisc** [comment]
Thanks, can you confirm:
- You are running Certify 3.0.11
- You are running as the normal Administrator account
- the Certify SSL Manager background service is running as the default Local System user (no modifications)
- What version of Windows Server are you running?

The usual reason for this error is that the IIS process cannot read the private key of the certificate, which normally happens if the the certificate is created by a user with different privileges. There are other intermittent reasons (messed up windows authentication) but these are usually solved with a reboot.

**Comment by kd8ssq** [comment]
- **You are running Certify 3.0.11:** Yes
- **You are running as the normal Administrator account:** Not the built-in account as this is reserved for our datacenter team.  We are running as a different full Admin account within the Administrators Group
- **the Certify SSL Manager background service is running as the default Local System user (no modifications);** Local System Account, no modifications
- **What version of Windows Server are you running?** Windows Server 2012 R2 Datacenter

**Comment by webprofusion-chrisc** [comment]
@kd8ssq Interesting! If you delete the existing https binding and then choose 'Re-apply Certificate to Bindings' do you get the same problem again? I assume there are no remnants of Let's Encrypt Win Simple still creating the same certificate anywhere.

**Comment by kd8ssq** [comment]
Yes, deleting the binding and then choosing 'Re-Apply Certificate to Bindings' does re-create the bindings and apply the certificate as it should.

I will note that right after the initial error yesterday, I did delete the Lets Encrypt Simple cert but I did not delete the bindings on the site.  They existed with No cert selected.  I tried clicking the 'Re-Apply Certificate to Bindings' button and it said it completed but didn't actually add the certs.  Do the bindings have to be deleted for the button to work?

**Comment by webprofusion-chrisc** [comment]
@kd8ssq No, not normally. There's an outside chance that the binding was created by the LEWS app and for some reason that caused an error if we try to update the same binding (as a different user). I'm just guessing, it's a pretty rare problem so far. I did uncover an actual bug in the IIS bindings admin API a while back, it's possibly related.

**Comment by kd8ssq** [comment]
@webprofusion-chrisc the bindings were initially created by me, not by the LEWS app.  

It's, probably some conflict between the apps, but figured I would let you know what I could in case it would help.

**Comment by webprofusion-chrisc** [comment]
Update: v4 now recreates existing bindings instead of updating the certificate hash.
