### ISSUE TITLE
no challenge found matching requested type

### ISSUE THREAD

**Issue by boscorelly** [webprofusion/certify#240]
Hi,

with last version : 

> 2018-01-12 12:12:57.541 +01:00 [INF] Beginning Certificate Request Process: Exchange
2018-01-12 12:12:57.541 +01:00 [INF] Registering Domain Identifiers
2018-01-12 12:12:57.541 +01:00 [INF] Attempting Domain Validation: webmail.*****.fr
2018-01-12 12:12:57.541 +01:00 [INF] Registering and Validating webmail.*****.fr 
2018-01-12 12:12:59.464 +01:00 [INF] Exchange: Request failed - no challenge found matching requested type
Parameter name: challengeType System.ArgumentOutOfRangeException: no challenge found matching requested type
Parameter name: challengeType
   at ACMESharp.AcmeClient.DecodeChallenge(AuthorizationState authzState, String challengeType) in D:\Work\GIT\certify\src\lib\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:line 423
   at Certify.ACMESharpCompat.ACMESharpUtils.CompleteChallenge(String identifierRef, String ChallengeType, String Handler, String HandlerProfileRef, Hashtable HandlerParameters, Boolean Force, Boolean CleanUp, Boolean Regenerate, Boolean Repeat, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 601
   at Certify.VaultManager.BeginRegistrationAndValidation(CertRequestConfig requestConfig, String identifierAlias, String challengeType, String domain) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 693
   at Certify.Management.APIProviders.ACMESharpProvider.BeginRegistrationAndValidation(CertRequestConfig config, String domainIdentifierId, String challengeType, String domain) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 103
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 527
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-01-12 12:12:59.465 +01:00 [INF] Exchange: Request failed - no challenge found matching requested type
Parameter name: challengeType System.ArgumentOutOfRangeException: no challenge found matching requested type
Parameter name: challengeType
   at ACMESharp.AcmeClient.DecodeChallenge(AuthorizationState authzState, String challengeType) in D:\Work\GIT\certify\src\lib\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:line 423
   at Certify.ACMESharpCompat.ACMESharpUtils.CompleteChallenge(String identifierRef, String ChallengeType, String Handler, String HandlerProfileRef, Hashtable HandlerParameters, Boolean Force, Boolean CleanUp, Boolean Regenerate, Boolean Repeat, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 601
   at Certify.VaultManager.BeginRegistrationAndValidation(CertRequestConfig requestConfig, String identifierAlias, String challengeType, String domain) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 693
   at Certify.Management.APIProviders.ACMESharpProvider.BeginRegistrationAndValidation(CertRequestConfig config, String domainIdentifierId, String challengeType, String domain) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 103
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 527
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420

**Comment by webprofusion-chrisc** [comment]
Hi, this error is caused by Let's Encrypt suddenly removing support for tls-sni-01 challenges (https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188)

The only solution is to use an alternate challenge type, which for Certify is http-01. Unfortunately this is beyond our control

**Comment by boscorelly** [comment]
Hi,

i have this error with http :

> 2018-01-12 12:56:02.537 +01:00 [INF] Validation of the required challenges did not complete successfully. Domain validation failed: webmail.peringenierie.fr

**Comment by webprofusion-chrisc** [comment]
@boscorelly Hi, it looks like your server is not responding to http requests on port 80, so you may need to add a binding to your website on port 80 to enable that, it can then redirect to https but it must respond to http first. Unfortunately that's a restriction of thehttp-01 challenge type. Basically you're trying to get your server to serve: http://webmail.peringenierie.fr/.well-known/acme-challenge/configcheck without any issues.

**Comment by webprofusion-chrisc** [comment]
p.s. if you do use a redirect to https and you use a temporary self-signed certificate that would work ok as well.
