### ISSUE TITLE
Unable to run manual manual certification renewals

### ISSUE THREAD

**Issue by vulwaowf** [webprofusion/certify#248]
I've noticed something odd when I attempt a manual renewal of multiple certificates.

If you select a domain in "managed sites", and then click on "request certificate" the renewal goes through fine.  However if you do the above and while the first renewal is in processing if you try a second you receive an error on one of the renewals.  If you attempt 4 manual renewals at the same time only 1/4 will succeed.

2018-01-24 10:54:08.868 -08:00 [INF] ************.com: Request failed - Unable to find a Certificate for the given reference System.Exception: Unable to find a Certificate for the given reference
   at Certify.ACMESharpCompat.ACMESharpUtils.UpdateCertificate(String certificateRef, String PkiTool, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 803
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 1194
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 139
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 682
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-01-24 10:54:08.872 -08:00 [INF] ************.com: Request failed - Unable to find a Certificate for the given reference System.Exception: Unable to find a Certificate for the given reference
   at Certify.ACMESharpCompat.ACMESharpUtils.UpdateCertificate(String certificateRef, String PkiTool, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 803
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 1194
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 139
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 682
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420

**Comment by vulwaowf** [comment]
![image](https://user-images.githubusercontent.com/30328500/35352462-fdbd537c-0111-11e8-979e-0ca9074060a6.png)

Screen shot of the error and error message from log file for each failure.


Domain One

2018-01-24 11:18:11.711 -08:00 [INF] Performing Config Tests
2018-01-24 11:18:17.861 -08:00 [INF] Pre-Request Script output: 
MSFT_ScheduledTask (TaskName = "SSL Challenge", TaskPath = "\")
2018-01-24 11:18:17.861 -08:00 [INF] Beginning Certificate Request Process: **domain.com**
2018-01-24 11:18:17.864 -08:00 [INF] Registering Domain Identifiers
2018-01-24 11:18:17.864 -08:00 [INF] Attempting Domain Validation: **domain.com**
2018-01-24 11:18:17.868 -08:00 [INF] Registering and Validating **domain.com** 
2018-01-24 11:18:20.566 -08:00 [INF] Domain already has current authorization, skipping verification: **domain.com**
2018-01-24 11:18:20.566 -08:00 [INF] Attempting Domain Validation: **sub.domain.com**
2018-01-24 11:18:20.568 -08:00 [INF] Registering and Validating **sub.domain.com** 
2018-01-24 11:18:24.896 -08:00 [INF] Could not begin authorization for domain with Let's Encrypt: [**sub.domain.com**] Could not register domain identifier - [11:18 AM] If the challenge response file is not accessible at this exact URL the validation will fail and a certificate will not be issued.
2018-01-24 11:18:26.345 -08:00 [INF] Validation of the required challenges did not complete successfully. [**sub.domain.com**] : 
2018-01-24 11:18:26.348 -08:00 [INF] Validation of the required challenges did not complete successfully. [**sub.domain.com**] : 
2018-01-24 11:18:26.985 -08:00 [INF] Post-Request Script output:
MSFT_ScheduledTask (TaskName = "SSL Challenge", TaskPath = "\")
2018-01-24 11:20:59.736 -08:00 [INF] Previous renewals failed: 12. Renewal will be attempted within 48hrs.

Domain Two

2018-01-24 11:18:15.378 -08:00 [INF] Performing Config Tests
2018-01-24 11:18:21.845 -08:00 [INF] Pre-Request Script output: 
MSFT_ScheduledTask (TaskName = "SSL Challenge", TaskPath = "\")

2018-01-24 11:18:21.845 -08:00 [INF] Beginning Certificate Request Process: **domain.com**
2018-01-24 11:18:21.849 -08:00 [INF] Registering Domain Identifiers
2018-01-24 11:18:21.849 -08:00 [INF] Attempting Domain Validation: **domain.com**
2018-01-24 11:18:21.855 -08:00 [INF] Registering and Validating **domain.com** 
2018-01-24 11:18:29.022 -08:00 [INF] Could not begin authorization for domain with Let's Encrypt: [**domain.com**] Could not register domain identifier - [11:18 AM] GetIdentifier : System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Certify.VaultManager.BeginRegistrationAndValidation(CertRequestConfig requestConfig, String identifierAlias, String challengeType, String domain) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 704
2018-01-24 11:18:30.746 -08:00 [INF] Validation of the required challenges did not complete successfully. [**domain.com**] : 
2018-01-24 11:18:30.750 -08:00 [INF] Validation of the required challenges did not complete successfully. [**domain.com**] : 
2018-01-24 11:18:31.334 -08:00 [INF] Post-Request Script output:
MSFT_ScheduledTask (TaskName = "SSL Challenge", TaskPath = "\")

If I run a renewal again within a few seconds it'll work as long as I do only one.

**Comment by webprofusion-chrisc** [comment]
Thanks for your info, if this just on the latest version?

I noticed you are running a custom task, does that do anything custom to allow your server to respond to validation challenges?

The "Could not register domain identifier" part is usually to do with hitting either a refusal from Let's Encrypt to register the domain identifier or a Let's Encrypt server error. The rate limit could be that we're hitting the server too fast. We should be logging those problems though which is why I wondered what version this was.

**Comment by vulwaowf** [comment]
I tried it on two versions.  I had to just do the renewal one by one.

The custom task copies the validation file to a group of servers.  This is so any server can answer the validation challenge in production.  But for some reason it wasn't working so I had to do each server individually.  So in this case it wasn't actually doing anything as all requests came directly to the server.

I'll have to get back to the syncing of the validation file to multiple servers at some point.

**Comment by tvanassche** [comment]
I'm experiencing the same problem when trying to renew multiple sites at once, either through the scheduler or manually. The same "Validation of the required challenges did not complete successfully." error pops up. And as vulwaowf mentioned, when doing only 1 renewal at a time, the problem doesn't occur.

And it seems to occur mostly with sites that have multiple bindings that need to be added to the certificate. Sites with 1 binding usually succeed without problems.

Running latest version (3.0.11).

**Comment by webprofusion-chrisc** [comment]
@tvanassche  do you have a Certify log file for one or more of the managed sites that you could pass to apps {at} webprofusion.com ?

Do each of your domains across the multiple managed sites all point to the same website or are they difference websites? Regarding wrong certificates etc that's very unlikely (i.e. nope) and the most likely issue is a configuration check failing (possibly for the wrong reasons). We have encountered issues with bindings having to be updated in quick succession causing issues but that happens after the cert has been acquired.

**Comment by tvanassche** [comment]
I've emailed the logs.

As for your question: Each of the failed sites has multiple domains pointing to the same website. One site has just under 100 domains, close to the Let’s Encrypt rate limit for domains per certificate.

I've checked the IIS logs for those sites at the time the failure happened, but I didn't see anything out of the ordinary.

**Comment by webprofusion-chrisc** [comment]
Thanks, so I think there's a couple of things we need to do:
- Add more tests for large requests so we can simulate these better
- Reduce the frequency of calls to the ACME API - we are probably hitting it too hard/too frequently.
- Better logging of the error we get back, there's probably a rate limit happening 

In addition to this, the upcoming ACME v2 API changes the process slightly - the domains you want to include are declared up front and a list of authorization to be completed (or already done) comes back, this will reduce traffic (and the likelihood of a single failure in the batch). 

Either way though we should expect the API to fail intermittently and so that's why 3.x onwards has the improved renewal process, basically it should eventually work even if it has a few failures to begin with. If you get a permanent failure, that's when we need to really investigate.

**Comment by webprofusion-chrisc** [comment]
Please comment if this is still an issue, v4 is now the production release.
