### ISSUE TITLE
Certify SSL Manager Crashing

### ISSUE THREAD

**Issue by adam0r** [webprofusion/certify#282]
- Windows Small Business Server 2011 Standard x64
- .NET Framework 4.7.1 / 
- Certify The Web version 3.0.11 [Community Edition]

Upon clicking 'New Certificate' button I receive the following:

`An error occurred: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List
![screenshot](https://user-images.githubusercontent.com/37955018/38162805-dbbb4246-34df-11e8-8440-02b9916acc68.PNG)
1[Certify.Models.SiteBindingItem]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Message', line 1, position 11.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Certify.Client.CertifyServiceClient.<GetServerSiteList>d__31.MoveNext() in D:\Work\GIT\certify\src\Certify.Client\CertifyServiceClient.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.UI.Controls.ManagedItemSettings.<MainViewModel_PropertyChanged>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.UI\Controls\ManagedItemSettings.xaml.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Certify.UI.App.Main()`

All Windows Updates performed, service packs applied - I'm stumped, never come across this before - It's always just *worked* perfectly!

**Comment by webprofusion-chrisc** [comment]
Thanks for logging this issue. The part that's failing is where it queries IIS for the list of sites that are setup. 

- Was the app working on this server previously? 

- Are there any new sites setup since it last worked?

- How many websites are currently configured in IIS?

**Comment by adam0r** [comment]
Hi Chris, thanks for the prompt reply.
- The app is new to this server, we're replacing an existing Comodo SSL Certificate and moving to LetsEncrypt
- There are 3 sites running on IIS; 
1. Default website (The site I want to add the SSL to; currently has an SSL cert binded to it) 
2. SBS Client Deployment  (Binded to SbsConnectComputer:80)
3. WSUS Administration
![image](https://user-images.githubusercontent.com/37955018/38163120-5549c91a-34e6-11e8-89da-0ebe0a942366.png)

**Comment by webprofusion-chrisc** [comment]
Thanks, that's an interesting one! Glad you found the issue, it sounds like the IIS configuration was slightly corrupted but we should still have been able to recover from that at least a little.

I note also that the default website has two https bindings, so be aware that the current version of the app will only update the first https binding it finds on the site, so you'd need to manually fix the certificate binding on the other https binding entry.

**Comment by adam0r** [comment]
Hopefully this helps someone out in the future, or an error can be produced with a bit more information. As you say, definitely looks like it was that malformed/corrupt entry that was doing it. I'm carrying out this work for a customer who's not what I'd consider a *'regular'* client, so I'll do some housekeeping whilst I'm in here, good to know about the multiple HTTPS bindings - Thanks for the heads up! 👍
