### ISSUE TITLE
PS Script with Parameters

### ISSUE THREAD

**Issue by sambasile** [webprofusion/certify#286]
My goal is to be able to turn rewrite rules the redirect to port 443 off prior to the certificate request and back on after the request is complete.  I am trying to do this with a PS script and parameters.

`param([string]$ruleName="Force to 443", [string]$sitePath="Default Web Site", [string]$enabled)
$theCmd = "/system.webserver/rewrite/rules/rule[@name=""{0}""]" -f$ruleName

Import-module webadministration
if ($enabled = 'true'){
    set-webconfigurationproperty $theCmd -Name enabled -Value true -PSPath $sitePath
} else {
    set-webconfigurationproperty $theCmd -Name enabled -Value false -PSPath $sitePath
}`

When I use:

_FullPathToScript_.ps1 -sitePath "iis:\sites\sitename" -enabled "false" in the Pre-request PS Script I get illegal character in path when using the double quotes.  

If I replace the double quotes with single quotes (_FullPathToScript_.ps1 -sitePath 'iis:\sites\sitename' -enabled 'false')  it triggers an exception in Certify and the program crashes.  (below)

Any help appreciated.  Thank you.

~~~~~~~

An error occurred: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in D:\Work\GIT\certify\src\Certify.Shared\Management\PowerShellManager.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.UI.Controls.ManagedItemSettings.<TestScript_Click>d__19.MoveNext() in D:\Work\GIT\certify\src\Certify.UI\Controls\ManagedItemSettings.xaml.cs:line 331
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Certify.UI.App.Main()

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this. So in the pre-request script text box you just have a file path to a .ps1 or you have arguments as well? Only a path to a file is supported currently.

Regarding the purpose of the script, you can leave https rewrites on as long as they take you to the same place so http://example.com/.well-known/acme-challenge/configcheck should/could redirect to https://www.example.com/.well-known/acme-challenge/configcheck

**Comment by sambasile** [comment]
Yes, I have the path to the script with arguments so thanks for pointing that out.

Thank you for your help.  Based upon your message I re-examined my URL rewrite and discovered a missing forward slash between the host and parameters url="https://{HTTP_HOST}{R:1}" (wrong) vs. url="https://{HTTP_HOST}/{R:1}" (correct).
