### ISSUE TITLE
Request failed - The file exists

### ISSUE THREAD

**Issue by Viashopia** [webprofusion/certify#289]
Hi,

since a few weeks, each time I try to renew a certificate, I receive the below error:

```
2018-04-14 21:15:59.583 +02:00 [INF] ws.viashopia.com: Request failed - The file exists.
 System.IO.IOException: The file exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Certify.ACMESharpCompat.ACMESharpUtils.UpdateCertificate(String certificateRef, String PkiTool, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 865
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 1194
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 139
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 682
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
```

Would anyone know which file it is trying to access? Should I purge temporary files somewhere?

It would be nice to state the name and path of the problem file in the exception to ease troubleshooting.

Thanks for your help
Best regards

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for raising this, I havaen't seen this before and it seems to be very uncommon. It looks like the temp file being created is coming back with a duplicate file (we just ask windows to give us a temp file path). 

From my understanding you should be able to clear out the contents of the TEMP folder which will either be in AppData or Windows folder.

https://stackoverflow.com/questions/3320203/what-folder-does-pathgettempfilename-method-save-to

You can browse to the temp folder by using Start > Run > %temp%

**Comment by webprofusion-chrisc** [comment]
Googling it a bit more, this is a common issue if your temp folder has a large number of file in it. Working out which app is creating all of the other temp files would be a solution, but clearing it out will temporarily resolve this.
