### ISSUE TITLE
Problem to renew certificate "System.IO.IOException The file exists"

### ISSUE THREAD

**Issue by p3junior** [webprofusion/certify#334]
When I'm trying renew the certificate, the system show me this error:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Certify.ACMESharpCompat.ACMESharpUtils.UpdateCertificate(String certificateRef, String PkiTool, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 865
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 1194
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 139
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 682
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420
2018-07-03 09:18:42.212 -03:00 [INF] wfmine: Request failed - The file exists.
 System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Certify.ACMESharpCompat.ACMESharpUtils.UpdateCertificate(String certificateRef, String PkiTool, String vaultProfile) in D:\Work\GIT\certify\src\Certify.Core\ACMESharpCompat\ACMESharpUtils.cs:line 865
   at Certify.VaultManager.PerformCertificateRequestProcess(String domainIdentifierRef, String[] alternativeIdentifierRefs) in D:\Work\GIT\certify\src\Certify.Core\Management\VaultManager.cs:line 1194
   at Certify.Management.APIProviders.ACMESharpProvider.PerformCertificateRequestProcess(String primaryDnsIdentifier, String[] alternativeDnsIdentifiers) in D:\Work\GIT\certify\src\Certify.Core\Management\APIProviders\ACMESharpProvider.cs:line 139
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__52.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 682
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__51.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager.cs:line 420

**Comment by webprofusion-chrisc** [comment]
Hi, this has come up before when windows has too many files under the Temp folder.

The location of the temp folder can vary but you can browse to it in Windows Explorer by going to %TEMP%

Windows has a limit of 65535 files under temp, including those in subfolders. If you clear out the temp folder I would expect this to start working again, you may also find other parts of windows/apps become more reliable as well. You might want to see if you can find any apps that are creating lots of temp files.

**Comment by p3junior** [comment]
Hi, it didn't work. I cleaned this folder and the error happened again. 

Other solution to try?

**Comment by p3junior** [comment]
I resolved it now installing the Beta Version 4.
