### ISSUE TITLE
Failed to finalize certificate order:  Error finalizing order :: policy forbids issuing (domain contains Swedish å)

### ISSUE THREAD

**Issue by stefanbg** [webprofusion/certify#335]
Version 4.0.1.40004

Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.CertificateChainExtensions.ToPfx(CertificateChain certificateChain, IKey certKey)
   at Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 298

**Comment by webprofusion-chrisc** [comment]
Thanks for the stack trace, anything unusual about the certificate being requested? Does the log file contain anything useful? Was the request delayed in any way (like paused as part of a manual DNS validation etc).

The piece of code that fails here is the very last step creating the certificate, so either we don't have the full certificate chain or the CSR signing key has an issue. This is far from normal.

**Comment by stefanbg** [comment]
Here's more:

Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.CertificateChainExtensions.ToPfx(CertificateChain certificateChain, IKey certKey)
   at Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 298
2018-07-04 00:03:01.383 +02:00 [INF] : Request failed - Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.CertificateChainExtensions.ToPfx(CertificateChain certificateChain, IKey certKey)
   at Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 298
2018-07-04 00:03:02.771 +02:00 [ERR] Certificate request process failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.CertificateChainExtensions.ToPfx(CertificateChain certificateChain, IKey certKey)
   at Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 298
System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.CertificateChainExtensions.ToPfx(CertificateChain certificateChain, IKey certKey)
   at Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 493
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 298

**Comment by stefanbg** [comment]
What's different is I have Swedish letter å in the domain like xyå.se

**Comment by webprofusion-chrisc** [comment]
@stefanbg it's possible but obviously it shouldn't be a problem and it's clearly a bug if it is. I've tested with other unicode domains without any issues, but I'll investigate. Are you using http validation or DNS?

**Comment by webprofusion-chrisc** [comment]
@stefanbg thanks, turns out that does break, which is great because it let's me work out a fix for it. This will be corrected in the next release (which should hopefully be the proper 4.0 release)

**Comment by stefanbg** [comment]
Glad if I can help in any small way to this great software. 

Well xzå.se is not my domain just an example :)

**Comment by stefanbg** [comment]
I also get the policy forbids issuing for: "xyå.se.<testdomain>"

Not sure if you´ve already seen this: 
https://community.letsencrypt.org/t/idn-support-enabled/21469 
Let’s Encrypt (and the ACME protocol) accept IDNs only as A-labels (ASCII labels, starting with xn--, also known as Punycode), not as U-labels (Unicode labels)

So looks like Certify needs to convert it to xn-- format before sending it.

**Comment by webprofusion-chrisc** [comment]
Thanks, the code to convert to ASCII before submitting the CSR was accidentally dropped during an update and has since been resolved in development, the next update (next week) will resolve this.
