### ISSUE TITLE
Error after upgraded to Windows Server 2019

### ISSUE THREAD

**Issue by YuriMyakotin** [webprofusion/certify#373]
Can’t renew certificates after upgraded my system from Windows Server 2016 to 2019. Every time getting this error:

2018-10-12 11:34:45.788 +03:00 [INF] A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
at Certify.Providers.Certes.CertesACMEProvider.d__22.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Certify.Management.CertifyManager.d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 586
2018-10-12 11:34:48.184 +03:00 [INF] Validation of the required challenges did not complete successfully. A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
at Certify.Providers.Certes.CertesACMEProvider.d__22.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Certify.Management.CertifyManager.d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 586
2018-10-12 11:34:48.184 +03:00 [INF] Validation of the required challenges did not complete successfully. A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
at Certify.Providers.Certes.CertesACMEProvider.d__22.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Certify.Management.CertifyManager.d__11.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 586

**Comment by YuriMyakotin** [comment]
Using latest version of Certify the Web.

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this. Server 2019 support is not yet tested but I'll start investigating.

**Comment by PromontoryProtean** [comment]
I'm happy to report that I have deployed Windows Server 2019 to Azure and installed Certify. I only have one site configured so far but I have not run into problems. Was the problem above already addressed?
Thanks,
John

**Comment by YuriMyakotin** [comment]
Installed latest version of Certify, now everything works ok.

**Comment by webprofusion-chrisc** [comment]
Ok, thanks. I'll close this issue and if any other 2019 specific items come up we'll log them as new issues.
