### ISSUE TITLE
Error during script test

### ISSUE THREAD

**Issue by InteXX** [webprofusion/certify#385]
I'm getting an error when I try to test the `RDPGatewayServices` example script:

    ---------------------------
    Powershell Output
    ---------------------------
    Error - ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find drive. A drive with the name 'RDS' does not exist.
       at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
       at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
       at Certify.Management.PowerShellManager.<>c__DisplayClass0_1.<RunScript>b__5() in D:\Work\GIT\certify\src\Certify.Shared\Management\PowerShellManager.cs:line 80
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in D:\Work\GIT\certify\src\Certify.Shared\Management\PowerShellManager.cs:line 89
    ---------------------------
    OK
    ---------------------------

Should I modify the script and change `RDS` to an actual drive letter?

I'm running this on Server Essentials 2016.

**Comment by webprofusion-chrisc** [comment]
Hi, we provide these example scripts as a convenience but the app assumes that your environment is configured with the software you need before you run scripts.

You should determine if you have the `RemoteDesktopServices` Powershell module installed to manage RDS first. 

I recommend you try using the powershell command line for the RemoteDesktopServices module first, to ensure your environment as the required pre-requisites.

From a quick google you could try a script like this:

```Powershell
Import-Module RemoteDesktopServices

Get-Command –Module RemoteDesktopServices
```

From : https://blogs.technet.microsoft.com/ptsblog/2011/12/09/extending-remote-desktop-services-using-powershell/#m1

**Comment by InteXX** [comment]
The problem ceased after a reboot.

This is a great utility. Thank you. Good job.
