### ISSUE TITLE
Error since upgrading to latest version

### ISSUE THREAD

**Issue by EddieGreen** [webprofusion/certify#398]
I recently upgraded to version 4.0.12 Since that time I receive a fatal application error message which closes the app and the service.

The crash occures at the point of ‘Performing Automated Certificate Binding’

Can anyone throw light on whay this occurs and how to resolve?

```
An error occurred: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:9696
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Client.CertifyServiceClient.<FetchAsync>d__25.MoveNext() in C:\Work\GIT\certify\src\Certify.Client\CertifyServiceClient.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Client.CertifyServiceClient.<BeginCertificateRequest>d__43.MoveNext() in C:\Work\GIT\certify\src\Certify.Client\CertifyServiceClient.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.UI.ViewModel.AppViewModel.<BeginCertificateRequest>d__111.MoveNext() in C:\Work\GIT\certify\src\Certify.UI\ViewModel\AppViewModel.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.UI.Controls.ManagedCertificate.ManagedCertificateSettings.<Button_RequestCertificate>d__10.MoveNext() in C:\Work\GIT\certify\src\Certify.UI\Controls\ManagedCertificate\ManagedCertificateSettings.xaml.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Certify.UI.App.Main()
```
[session.log](https://github.com/webprofusion/certify/files/2666331/session.log)
[log_afef8569-36a6-4e5a-a009-0a234f8e966f_19.txt](https://github.com/webprofusion/certify/files/2666332/log_afef8569-36a6-4e5a-a009-0a234f8e966f_19.txt)
[ui.log](https://github.com/webprofusion/certify/files/2666333/ui.log)

**Comment by EddieGreen** [comment]
There is no `service.exceptions.log` in ProgramData

The background service is indeed crashing.

Looking in Windows Applications Log, three entries at the time of the crash (in time order):

![errors](https://user-images.githubusercontent.com/5681968/49788947-9e383800-fd22-11e8-9609-908bdbbd31f5.jpg)

### .NET Runtime:
```
   at System.Net.Http.HttpClientHandler.GetResponseCallback(System.IAsyncResult)

Exception Info: System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Certify.Client.CertifyServiceClient+<FetchAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Certify.Client.CertifyServiceClient+<BeginCertificateRequest>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Certify.UI.ViewModel.AppViewModel+<BeginCertificateRequest>d__111.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Certify.UI.Controls.ManagedCertificate.ManagedCertificateSettings+<Button_RequestCertificate>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Certify.UI.App.Main()
```
### Application Error:
```
Faulting application name: Certify.UI.exe, version: 4.0.0.0, time stamp: 0x5c061d70
Faulting module name: KERNELBASE.dll, version: 6.2.9200.22376, time stamp: 0x5a90c314
Exception code: 0xe0434352
Fault offset: 0x000000000000a06c
Faulting process ID: 0x1a78
Faulting application start time: 0x01d491183ed0fa59
Faulting application path: C:\Program Files\CertifyTheWeb\Certify.UI.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report ID: b9c9dca8-fd0c-11e8-9443-020025bbb6f8
Faulting package full name: 
Faulting package-relative application ID: 
```

### Certify.Service:
`Service started successfully.`

I experienced repeated crashes a couple of days ago. Today I removed all of the managed certificates from the app and then deleted the apps - there was a version 2, 3 and 4 installed - and cleaned everything except ProgramData.

I performed a fresh install of 4.0.12 and began adding the managed domains to the app. The first two failed renewal due to previous errors having maxed out the rate limit. The third looks like it got a certificate and crashed at a later point.

Long and short of this is that there are no settings to show you for the existing certificates retrieved with the app and it's not possible to re-apply bindings.

The preview of bindings for the failed domain are:

![bindings preview](https://user-images.githubusercontent.com/5681968/49788749-16eac480-fd22-11e8-8877-02fd442c15d2.jpg)

**Comment by webprofusion-chrisc** [comment]
I'll be releasing an update with extended logging, I'll probably do it as a beta and email you the link within the next day or so.

**Comment by webprofusion-chrisc** [comment]
Closing in preference to more specific bug #399
