### ISSUE TITLE
Error renewing certificate

### ISSUE THREAD

**Issue by jordanwallwork** [webprofusion/certify#411]
Getting the following error, running version 4.0.12.0. I recently upgraded to the 'Professional' licence, can't imagine that's the cause but mentioning it just in case.

```
2018-12-20 09:22:08.777 +00:00 [INF] Validation of the required challenges did not complete successfully. A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Providers.Certes.CertesACMEProvider.<SubmitChallenge>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext() in C:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 592
```

**Comment by webprofusion-chrisc** [comment]
Hi Jordan, no this is unrelated to registering an app key.  Could you try the 4.1.0 beta and see if it makes any difference - there have been a few bug fixes included and there's an outside chance it will help. 

If it doesn't help, can you try to enable verbose logging by adding/editing `c:\programdata\certify\serviceconfig.json` e.g.:

```json
{
 "loglevel":"verbose",

}
```

Then restarting the Certify background service under windows services (and the UI). Now when you make your request details http logs will be stored to C:\ProgramData\Certify\log\session.log

I don't recommend sharing those logs here as they may contain sensitive info, but have a look through them and see if there is an error from the Let's Encrypt API (towards the end of the log).

**Comment by webprofusion-chrisc** [comment]
Fixed in latest release.
