### ISSUE TITLE
PFX file is corrupted

### ISSUE THREAD

**Issue by ndouthit** [webprofusion/Certify#42]
When trying to create a new certificate, I get the following error message "An error occurred installing the certificate. Certificate file may not be a valid." A PFX file gets created but it is corrupt. The file size is 0 KB and I get an invalid file message when trying to open it. Since the file is corrupted, it is unable to be imported/installed.

I think I tracked down the issue though. In the VaultManager.CreateCertificate method there is a call to PowershellManager.SubmitCertificate. The SubmitCertificate has force set to true. If I change force to false, the PFX is successfully created and installed.

What's the purpose of using force? Any idea why it won't work on my machine?

Here is the log for reference:
```
[4:39 PM] Powershell: Initialize-ACMEVault -BaseURI https://acme-staging.api.letsencrypt.org/
[4:39 PM] Powershell: New-ACMERegistration -Contacts mailto:email@email.com
[4:39 PM] Powershell: Update-ACMERegistration -AcceptTOS
[4:39 PM] Powershell: New-ACMEIdentifier -Dns example.com -Alias example.com -Label Identifier:example.com
[4:39 PM] Powershell: Complete-ACMEChallenge -Ref example.com -ChallengeType http-01 -Handler manual  -Regenerate
[4:39 PM] Powershell: Submit-ACMEChallenge -Ref example.com -Challenge http-01
[4:39 PM] Powershell: Update-ACMEIdentifier -Ref example.com
[4:39 PM] Powershell: Update-ACMEIdentifier -Ref example.com
[4:40 PM] Powershell: New-ACMECertificate -Identifier example.com -Alias cert_example.com -Generate
[4:40 PM] Powershell: Submit-ACMECertificate -Ref cert_example.com
[4:40 PM] [Error]: System.Management.Automation.CmdletInvocationException: asset file already exists ---> System.IO.IOException: asset file already exists
   at ACMESharp.Vault.Providers.LocalDiskVault.CreateAsset(VaultAssetType type, String name, Boolean isSensitive, Boolean getOrCreate)
   at ACMESharp.POSH.SubmitCertificate.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.InvokeCurrentPSCommand() in D:\Development\Source\Repos\Certify\src\Certify.Core\Management\PowershellManager.cs:line 94
[4:40 PM] Powershell: Update-ACMECertificate -Ref cert_example.com
[4:40 PM] Powershell: Get-ACMECertificate -Ref =7b2dadb2-d9cb-4a90-b977-7364e1e30536 -ExportPkcs12 C:\ProgramData\ACMESharp\sysVault\99-ASSET\7b2dadb2-d9cb-4a90-b977-7364e1e30536-all.pfx -Overwrite
[4:40 PM] [Error]: System.Management.Automation.CmdletInvocationException: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch ---> OpenSSL.Core.OpenSslException: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
   at OpenSSL.Core.Native.ExpectNonNull(IntPtr ptr)
   at OpenSSL.X509.PKCS12..ctor(String password, CryptoKey key, X509Certificate cert, Stack`1 ca)
   at ACMESharp.PKI.Providers.OpenSslLibBaseProvider.ExportArchive(PrivateKey pk, IEnumerable`1 certs, ArchiveFormat fmt, Stream target, String password)
   at ACMESharp.PKI.Providers.OpenSslLibProvider.ExportArchive(PrivateKey pk, IEnumerable`1 certs, ArchiveFormat fmt, Stream target, String password)
   at ACMESharp.POSH.GetCertificate.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.InvokeCurrentPSCommand() in D:\Development\Source\Repos\Certify\src\Certify.Core\Management\PowershellManager.cs:line 94
[4:40 PM] Powershell: Update-ACMEIdentifier -Ref example.com
```

**Comment by soundshed** [comment]
Sorry, I'd have to dig into ACMESharp but I think this was an issue overwriting the certificate in the vault.

**Comment by soundshed** [comment]
Resolved.
