### ISSUE TITLE
Microsoft Management Infrastructure error in 4.1.3

### ISSUE THREAD

**Issue by manikmakki** [webprofusion/certify#427]
I'm still having the Microsoft Management Infrastructure error in version 4.1.3.
I have Certify The Web installed on a 2008R2 machine.

````
2019-01-28 15:24:32.105 -08:00 [INF] Requesting Validation from Let's Encrypt: (mydomain).com
2019-01-28 15:24:32.105 -08:00 [INF] Attempting Domain Validation: *.(mydomain).com
2019-01-28 15:24:32.105 -08:00 [INF] Registering and Validating *.(mydomain).com 
2019-01-28 15:24:32.105 -08:00 [INF] Performing automated challenge responses (*.(mydomain).com)
2019-01-28 15:24:32.108 -08:00 [ERR] DNS update failed: DNS Challenge API Provider could not be created. Check all required credentials are set. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Certify.Core.Management.Challenges.ChallengeProviders.<GetDnsProvider>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Certify.Core.Management.Challenges.ChallengeProviders.GetDnsProvider(String providerType, Dictionary`2 credentials, Dictionary`2 parameters, ILog log)
   at Certify.Core.Management.Challenges.DnsChallengeHelper.<CompleteDNSChallenge>d__2.MoveNext() in C:\Work\GIT\certify\src\Certify.Core\Management\Challenges\DNS\DnsChallengeHelper.cs:line 135

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by webprofusion-chrisc** [comment]
4.1.4 release now anyway as this will affect other users, let me know if it resolves the problem for you. 

I believe the full corrective action is to install the latest compatible version of the Windows Management Framework, however if you are running other services it's best to check compatibility first.

https://docs.microsoft.com/en-us/powershell/wmf/overview
