### ISSUE TITLE
urn:ietf:params:acme:error:badNonce: JWS has an invalid anti-replay nonce

### ISSUE THREAD

**Issue by philjones88** [webprofusion/certify#441]
I'm trying to figure out why my website and IIS are out of sync.

IIS and Certify both say the certificate it valid and freshly requested however visiting the site still shows an old certificate.

I've delete and re-added the IIS site in Certify to no joy. Deleted bindings. Deleted old certificates. Still old certificate that expired 8 days ago.

This is the log for the site:

```
2019-02-20 16:38:46.487 +00:00 [INF] All Tests Completed OK
2019-02-20 16:38:57.668 +00:00 [INF] Certify/4.1.4.0 (Windows; Microsoft Windows NT 6.2.9200.0) 
2019-02-20 16:38:57.669 +00:00 [INF] Beginning Certificate Request Process: Escape.EN using ACME Provider:Certes
2019-02-20 16:38:57.669 +00:00 [INF] Registering Domain Identifiers
2019-02-20 16:38:57.669 +00:00 [ERR] BeginCertificateOrder: creating/retrieving order. Retries remaining:2 
2019-02-20 16:38:59.736 +00:00 [ERR] BeginCertificateOrder: error creating order. Retries remaining:1 Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-order'.
urn:ietf:params:acme:error:badNonce: JWS has an invalid anti-replay nonce: "qdhx___________ftE"
   at Certes.Acme.IAcmeHttpClientExtensions.<Post>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.AcmeContext.<NewOrder>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.Certes.CertesACMEProvider.<BeginCertificateOrder>d__26.MoveNext() 
2019-02-20 16:39:00.749 +00:00 [ERR] BeginCertificateOrder: creating/retrieving order. Retries remaining:0 
2019-02-20 16:39:01.461 +00:00 [INF] Created ACME Order: https://acme-v02.api.letsencrypt.org/acme/order/45_____3/32_____58
2019-02-20 16:39:02.258 +00:00 [INF] Fetching Authorizations.
2019-02-20 16:39:05.949 +00:00 [INF] Got http-01 challenge https://acme-v02.api.letsencrypt.org/acme/challenge/f201_______U0/123____4
2019-02-20 16:39:07.353 +00:00 [INF] Got dns-01 challenge https://acme-v02.api.letsencrypt.org/acme/challenge/f201_____U0/123___2
2019-02-20 16:39:10.556 +00:00 [INF] Got http-01 challenge https://acme-v02.api.letsencrypt.org/acme/challenge/fIO2______Og/123_____5
2019-02-20 16:39:12.071 +00:00 [INF] Got dns-01 challenge https://acme-v02.api.letsencrypt.org/acme/challenge/fIO2______Og/123_____3
2019-02-20 16:39:12.071 +00:00 [INF] Order authorizations already completed.
2019-02-20 16:39:12.071 +00:00 [INF] Requesting Certificate via Let's Encrypt
2019-02-20 16:39:21.112 +00:00 [INF] Completed Certificate Request.
2019-02-20 16:39:21.151 +00:00 [INF] Performing Automated Certificate Binding
2019-02-20 16:39:22.435 +00:00 [INF] Completed certificate request and automated bindings update (IIS)
2019-02-20 16:39:24.087 +00:00 [INF] Request completed

```

I've redacted what I think to be sensitive, let me know if you need any of it.

**Comment by philjones88** [comment]
Rebooted server after windows updated and the new renewed certificate is working again. don't know if that exception is misleading.

**Comment by webprofusion-chrisc** [comment]
Hi Phil, we retry the order because the Let's Encrypt API doesn't make any gaurantees and it looks like the final retry worked ok.

Can you please review the Preview tab to ensure that the next renewal will definitely update the  correct binding(s). This is listed at the bottom of the page (the top of the page just shows which domains will be on the cert).
