### ISSUE TITLE
NullReferenceException during renewal

### ISSUE THREAD

**Issue by mb300sd** [webprofusion/certify#449]
Keep getting this error when I try to renew a cert with 4 domains (xxxxxx.com, xxxxxx.net, *.xxxxxx.com, *.xxxxxx.net)

Other certificates are working that have only xxx.xxx and *.xxx.xxx

2019-03-22 19:27:52.284 -04:00 [INF] Requesting Validation from Let's Encrypt: xxxxxx.com
2019-03-22 19:32:53.751 -04:00 [INF] Attempting Challenge Response Validation for Domain: xxxxxx.net
2019-03-22 19:32:53.751 -04:00 [INF] Registering and Validating xxxxxx.net 
2019-03-22 19:32:53.752 -04:00 [INF] Domain already has current authorization, skipping verification: xxxxxx.net
2019-03-22 19:32:53.752 -04:00 [INF] Attempting Challenge Response Validation for Domain: *.xxxxxx.com
2019-03-22 19:32:53.752 -04:00 [INF] Registering and Validating *.xxxxxx.com 
2019-03-22 19:32:53.752 -04:00 [INF] Checking automated challenge response for Domain: *.xxxxxx.com
2019-03-22 19:32:53.884 -04:00 [INF] A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Providers.Certes.CertesACMEProvider.<SubmitChallenge>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__12.MoveNext() in C:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 632
2019-03-22 19:32:54.738 -04:00 [INF] Validation of the required challenges did not complete successfully. A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Providers.Certes.CertesACMEProvider.<SubmitChallenge>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__12.MoveNext() in C:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 632
2019-03-22 19:32:54.739 -04:00 [INF] Validation of the required challenges did not complete successfully. A problem occurred while checking challenge responses: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Providers.Certes.CertesACMEProvider.<SubmitChallenge>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__12.MoveNext() in C:\Work\GIT\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.CertificateRequest.cs:line 632

**Comment by webprofusion-chrisc** [comment]
Hi, please try out 4.1.6 and if you have no luck with that please send your log file for this managed certificate to support at certifytheweb.com.

**Comment by mb300sd** [comment]
Update fixed the exception, but now I'm getting a new error.

2019-03-26 16:09:16.641 -04:00 [INF] DNS: Creating TXT Record '_acme-challenge.xxxxxxxx.com' with value 'WbQ_xxxxxxxxxxxxxxxxxxxxxxxxxxxBxY', in Zone Id 'xxxxxxxx.com' using API provider '(Use Custom Script)'
2019-03-26 16:09:21.544 -04:00 [INF] DNS: (Use Custom Script) :: 
C:\Program Files\CertifyTheWeb>cd /D "C:\Users\Administrator\Documents\" 

C:\Users\Administrator\Documents>powershell -File CertifyCreate.ps1 "xxxxxxxx.com" "_acme-challenge.xxxxxxxx.com" "WbQ_xxxxxxxxxxxxxxxxxxxxxxxxxxxxY" "xxxxxxxx.com" 
xxxxxxxx.com
_acme-challenge.xxxxxxxx.com
_acme-challenge
WxxxxxxxxxxxxxxxxxxxxxBxY

2019-03-26 16:09:21.545 -04:00 [INF] Requesting Validation from Let's Encrypt: xxxxxxxx.com
2019-03-26 16:14:22.718 -04:00 [INF] Attempting Challenge Response Validation for Domain: xxxxxxxx.net
2019-03-26 16:14:22.718 -04:00 [INF] Registering and Validating xxxxxxxx.net 
2019-03-26 16:14:22.718 -04:00 [INF] Domain already has current authorization, skipping verification: xxxxxxxx.net
2019-03-26 16:14:22.718 -04:00 [INF] Attempting Challenge Response Validation for Domain: *.xxxxxxxx.com
2019-03-26 16:14:22.719 -04:00 [INF] Registering and Validating *.xxxxxxxx.com 
2019-03-26 16:14:22.719 -04:00 [INF] Checking automated challenge response for Domain: *.xxxxxxxx.com
2019-03-26 16:14:22.724 -04:00 [INF] Challenge could not be submitted. No matching attempted challenge.
2019-03-26 16:14:24.068 -04:00 [INF] Validation of the required challenges did not complete successfully. Challenge could not be submitted. No matching attempted challenge.
2019-03-26 16:14:24.069 -04:00 [INF] Validation of the required challenges did not complete successfully. Challenge could not be submitted. No matching attempted challenge.

**Comment by webprofusion-chrisc** [comment]
Hi, please email your full log file through to support at certifytheweb.com - it appears that let's encrypt is not issuing a challenge for one or more of your domains, which may be domain specific.

**Comment by mb300sd** [comment]
I recreated the certificate and the problem seems to have gone away.
