### ISSUE TITLE
Unable to submit certificate after latest commit

### ISSUE THREAD

**Issue by ndouthit** [webprofusion/Certify#45]
Previously, I was able to fully create certificates and bind them to IIS. Now I can't get past the Submit-ACMECertificate step.

```
System.Management.Automation.CmdletInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: unresolved architecture-specific implementation
   at ACMESharp.PKI.Providers.OpenSslLibProvider..ctor(IReadOnlyDictionary`2 newParams)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at ACMESharp.PKI.CertificateProvider.GetProvider(String name, IReadOnlyDictionary`2 initParams)
   at ACMESharp.POSH.SubmitCertificate.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.SubmitCertificate(String certAlias, Boolean force) in D:\Development\Source\Repos\Certify\src\Certify.Core\Management\PowershellManager.cs:line 285
   at Certify.VaultManager.CreateCertificate(String domainAlias) in D:\Development\Source\Repos\Certify\src\Certify.Core\Management\VaultManager.cs:line 383
```

**Comment by soundshed** [comment]
Is this using your own build? Looks like it can't find the Open SSL libraries.  If so you might need to revert to the official download.

Note that the current master on github is a work in progress. I'm currently reworking/refactoring the request/renewal process because it's a bit disorganized and doesn't seem to work with the current ACMESharp from nuget.

**Comment by ndouthit** [comment]
Yeah I'm using my own build. I was playing around with the renewal process as well. It was working prior to the merge of gui-revisions into the master branch, but now it doesn't.

Just wanted to give you a heads up. Not really sure what caused it to stop working.

**Comment by soundshed** [comment]
Ok I'll see if I can find the difference, either way as soon as I get request/renewal working again on my machine I'll check it in. Part of the renewal issue has been around re-using identifiers which we shouldn't be doing.

**Comment by soundshed** [comment]
Main issue was a package reference, other issues were with Identifier reuse (each domain gets an identifier, this then becomes invalid after something like 290 days).

**Comment by soundshed** [comment]
Resolved.
