### ISSUE TITLE
[v5] Deployment Tasks: Start service works, but throws a timeout error

### ISSUE THREAD

**Issue by JLJTGR** [webprofusion/certify#501]
**Version:** 5.0.7.0

```
2020-05-17 04:06:40.412 -04:00 [INF] ---- Performing Task [On-Demand or Manual Execution] :: Start hMailServer ----
2020-05-17 04:06:40.413 -04:00 [INF] Task [Start hMailServer] :: Task is enabled and primary request was successful.
2020-05-17 04:06:40.414 -04:00 [INF] Starting service [hMailServer] 
2020-05-17 04:07:00.588 -04:00 [ERR] Start hMailServer (Stop, Start or Restart a Service) :: Task Failed with Exception :: System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Certify.Providers.DeploymentTasks.Core.ServiceManager.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.DeploymentTask.<Execute>d__10.MoveNext()
```
The service is successfully starts near the beginning.

**Comment by webprofusion-chrisc** [comment]
Thanks, I'll check it out. The services I tested started ok but the timeout is there for this purpose, perhaps extending the timeout would help. I think I have hmailserver so I'll see if I can reproduce the issue.

**Comment by JLJTGR** [comment]
Changing the timeout or service doesn't help.  My assumption is that `WaitForStatus()` is being passed `ServiceControllerStatus.Stopped` because the GUI only reports success when I use **services.msc** to stop the tested service.

**Comment by soundshed** [comment]
Thanks, you're correct. The real reason for this was my testing was extremely sloppy for this feature, whereas yours has been much appreciated - I added it on a whim and I probably shouldn't have done so until there was more time to test etc. Fix in the next version.

**Comment by webprofusion-chrisc** [comment]
Thanks, you're correct. The real reason for this was my testing was extremely sloppy for this feature, whereas yours has been much appreciated - I added it on a whim and I probably shouldn't have done so until there was more time to test etc. Fix in the next version.
