### ISSUE TITLE
UPGRADE ISSUE: Failure with Route53 API DNS-01 request/validation

### ISSUE THREAD

**Issue by areis422** [webprofusion/certify#516]
Receiving the following error. All tests succeed.

2020-08-05 14:21:37.862 -05:00 [ERR] [Post-Request Webhook] (Run Powershell Script) :: Task Failed with Exception :: System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in C:\Work\GIT\certify_5.0.x\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.PowershellScript.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.DeploymentTask.<Execute>d__10.MoveNext() in C:\Work\GIT\certify_5.0.x\certify\src\Certify.Core\Management\DeploymentTasks\DeploymentTask.cs:line 39
2020-08-05 14:21:37.862 -05:00 [INF] [Post-Request Webhook] :: [Post-Request Webhook] (Run Powershell Script) :: Task Failed with Exception :: System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in C:\Work\GIT\certify_5.0.x\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.PowershellScript.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.DeploymentTask.<Execute>d__10.MoveNext() in C:\Work\GIT\certify_5.0.x\certify\src\Certify.Core\Management\DeploymentTasks\DeploymentTask.cs:line 39
2020-08-05 14:21:37.862 -05:00 [INF] Deployment Tasks did not complete successfully.

**Comment by areis422** [comment]
More info: on upgrade to latest V5, converts existing webhook into powershell script call instead of keeping it as a webook.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for raising this, bug confirmed. An update will be released with a workaround for failed migrations in the next couple of days. Our webhook stuff clearly doesn't get an awful lot of use which is why it's taken 3 months for anyone to find this bug, so if you could edit your deployment task to call the correct webhook and confirm that works normally that would be great.

**Comment by areis422** [comment]
Upon first launch after upgrade, as long as you edit and change it
immediately from run a powershell script back to webhook, it preserves the
settings.

Confirmed that it does still work overall (posting to a webhook in a
Microsoft teams channel)
