### ISSUE TITLE
Trying to renew in Google Cloud DNS

### ISSUE THREAD

**Issue by jmpenalosa** [webprofusion/certify#517]
Hi,

I'm getting this error when trying to run updating certificates using the UI installed in a Windows Box.

I did specify the path of the json file in the UI as well, but it doesn't seem to work. It cannot update the DNS record.

2020-08-07 11:56:09.808 -04:00 [INF] DNS: Creating TXT Record '_acme-challenge.editedthisforpost.net' with value 'gu80zY7wEEO5TDiTroy5tSoye7MwV_8EGK1_QjjfRUw', in Zone Id '' using API provider 'Powershell/PoshACME DNS'

2020-08-07 11:56:10.026 -04:00 [ERR] DNS update failed: Powershell/PoshACME DNS :: Error - ParameterBindingValidationException: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets, Dictionary2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags, ParameterBindingException& bindingException) at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection1 unboundArguments, UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection1 arguments) at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection1 arguments)
at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for reporting this issue. Can you confirm the you are:
- Using the latest version (v5.0.12) of Certify The Web
- Specifying the full file path to your Google Cloud key file (json format).

Can you then also confirm that the contents of the google cloud key file looks similar to this (with different values):

```
{
  "type": "service_account",
  "project_id": "something",
  "private_key_id": "9316786e5a8dc3a74f5ac15e5e16074af2b907f2",
  "private_key": "-----BEGIN PRIVATE KEY-----...QkbRkjU5Nd/Zc0o5Rl\n-----END PRIVATE KEY-----\n",
  "client_email": "certify@something.iam.gserviceaccount.com",
  "client_id": "902463483627068137432",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/certify%40something.iam.gserviceaccount.com"
}
```

**Comment by jmpenalosa** [comment]
Hi @webprofusion-chrisc 

Thank you for checking.

Yes, I confirm that the key looks like that. I generated two different keys just to try, same result. I confirm that I gave the service account DNS administrator role in GCP.

It seems to be able to use the key because it's able to read the existing _acme TXT record but is unable to write due to an empty parameter in URI error. 

I also confirm that I am using the latest version
![image](https://user-images.githubusercontent.com/49530001/89736902-fb761680-da3a-11ea-95c3-33cd61950359.png)

The whole log is below:  at Certify.Providers.ACME.Certes.CertesACMEProvider.<BeginCertificateOrder>d__30.MoveNext() in C:\Work\GIT\certify_5.0.x\certify\src\Certify.Providers\ACME\Certes\CertesACMEProvider.cs:line 566
2020-08-07 14:02:58.013 -04:00 [ERR] BeginCertificateOrder: error creating order. Retries remaining:1 :: JWS has an invalid anti-replay nonce: "0102XdJU3h58fnRICVUtl_fpdBRoyW2eMvZH5mDCj2_uJIQ" 
2020-08-07 14:02:59.014 -04:00 [INF] BeginCertificateOrder: creating/retrieving order. Retries remaining:0 
2020-08-07 14:02:59.176 -04:00 [INF] Created ACME Order: https://acme-v02.api.letsencrypt.org/acme/order/81527594/4575978086
2020-08-07 14:02:59.316 -04:00 [INF] Fetching Authorizations.
2020-08-07 14:03:00.144 -04:00 [INF] Got dns-01 challenge https://acme-v02.api.letsencrypt.org/acme/chall-v3/6379630519/uCblwQ
2020-08-07 14:03:00.144 -04:00 [INF] Attempting Domain Validation: *.REMOVEDFORTHEPOST.net
2020-08-07 14:03:00.146 -04:00 [INF] Registering and Validating *.REMOVEDFORTHEPOST.net 
2020-08-07 14:03:00.147 -04:00 [INF] Performing automated challenge responses (*.REMOVEDFORTHEPOST.net)
2020-08-07 14:03:00.147 -04:00 [INF] DNS: Creating TXT Record '_acme-challenge.REMOVEDFORTHEPOST.net' with value 'ROG_Dk6T1-iyEIOjht4oKjHSRt0cKs0s5XUQFgdd0zM', in Zone Id '' using API provider 'Powershell/PoshACME DNS'
2020-08-07 14:03:00.343 -04:00 [ERR] DNS update failed: Powershell/PoshACME DNS :: Error - ParameterBindingValidationException: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets, Dictionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags, ParameterBindingException& bindingException)
   at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments, UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2020-08-07 14:03:00.343 -04:00 [INF] Requesting Validation: *.REMOVEDFORTHEPOST.net
2020-08-07 14:03:30.453 -04:00 [INF] Attempting Challenge Response Validation for Domain: *.REMOVEDFORTHEPOST.net
2020-08-07 14:03:30.454 -04:00 [INF] Registering and Validating *.REMOVEDFORTHEPOST.net 
2020-08-07 14:03:30.454 -04:00 [INF] Checking automated challenge response for Domain: *.REMOVEDFORTHEPOST.net
2020-08-07 14:03:30.655 -04:00 [WRN] Challenge response validation still pending. Re-checking [10]..
2020-08-07 14:03:32.293 -04:00 [INF] Incorrect TXT record "pm3Zz66U3BqNIosOK6qVsGMDZSBaH2cw6p1W6Y7wGbU" found at _acme-challenge.REMOVEDFORTHEPOST.net
2020-08-07 14:03:33.130 -04:00 [INF] DNS: Deleting TXT Record '_acme-challenge.REMOVEDFORTHEPOST.net', in Zone Id '' using API provider 'Powershell/PoshACME DNS'
2020-08-07 14:03:33.756 -04:00 [INF] Validation of the required challenges did not complete successfully. Incorrect TXT record "pm3Zz66U3BqNIosOK6qVsGMDZSBaH2cw6p1W6Y7wGbU" found at _acme-challenge.REMOVEDFORTHEPOST.net
2020-08-07 14:03:33.756 -04:00 [INF] Validation of the required challenges did not complete successfully. Incorrect TXT record "pm3Zz66U3BqNIosOK6qVsGMDZSBaH2cw6p1W6Y7wGbU" found at _acme-challenge.REMOVEDFORTHEPOST.net
2020-08-07 14:03:33.758 -04:00 [INF] Validation of the required challenges did not complete successfully. Incorrect TXT record "pm3Zz66U3BqNIosOK6qVsGMDZSBaH2cw6p1W6Y7wGbU" found at _acme-challenge.REMOVEDFORTHEPOST.net

**Comment by webprofusion-chrisc** [comment]
Thanks, so I tested this yesterday with a new service account and got a 403 error, I created yet another new account in a new project today with the custom defined role in Google Cloud exactly as defined in this document: https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/GCloud-Readme.md and it's working for me as it should.

Can you trying to use Posh-ACME directly to confirm that your environment/key are correct? This is the script I used, you just need to specify your domain and key file:

```ps
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
Import-Module Posh-ACME
New-PACertificate test.domain.co.uk -DnsPlugin GCloud -PluginArgs @{GCKeyFile='C:\Temp\keyfilejson'}
```


The `URI` field I think that's being problematic is an http call from powershell and clearly it works for me (on 2 different machines) and not for you, which suggests it could be powershell version related. Note that the base requirements for Posh-ACME are slightly different from Certify: https://github.com/rmbolger/Posh-ACME#requirements-and-platform-support

**Comment by jmpenalosa** [comment]
Hi @webprofusion-chrisc 

Thank you. The powershell version is 4.0 

From the looks of it, once I get the necessary modules installed, it should already work.

Thanks for your help!
