### ISSUE TITLE
SimpleDNS Plus API not working in 5.0.12.0

### ISSUE THREAD

**Issue by posixx** [webprofusion/certify#521]
I have installed this version form scracht and am not able to use the SimpleDNSPlus proivder. Previous version (befor 5.0) work fine using the same simpleDNS server. Error:

DNS update failed: Failed [SimpleDNSPlus DNS API]: Object reference not set to an instance of an object
 Credentials are validating fine

Any idea?

**Comment by webprofusion-chrisc** [comment]
Hi, it could still be credential related if the app is having trouble decrypting a previoulsy stored credential for some reason. Please try out the following test version, this includes a more detailed error which will show us more about the exception

: https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/archive/CertifyTheWebSetup_V5.1.1.exe

**Comment by posixx** [comment]
I have uninstalled v5 and installed 4.1.8 on this server. After adding the credentials again and requesting certificate it works, so i'm sure it's related to the v5 version,,

I installed the testversion on a win10 system and tried again:

2020-08-19 13:49:46.458 +02:00 [INF] DNS: Creating TXT Record '_acme-challenge.test.yodacloud.net' with value 'J53HWvTZ1RbYnluPya6nY9CIiUSIgPkr8KszIWbN5mY', in Zone Id 'yodacloud.net' using API provider 'SimpleDNSPlus DNS API'
2020-08-19 13:49:46.556 +02:00 [ERR] DNS update failed: Failed [SimpleDNSPlus DNS API]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Models.Providers.DnsProviderBase.<>c__DisplayClass0_0.<DetermineZoneDomainRoot>b__0(DnsZone z) in C:\Work\GIT\certify_dev\certify\src\Certify.Models\Providers\IDnsProvider.cs:line 96
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Certify.Models.Providers.DnsProviderBase.<DetermineZoneDomainRoot>d__0.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Models\Providers\IDnsProvider.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DNS.SimpleDNSPlus.DnsProviderSimpleDNSPlus.<CreateRecord>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Core.Management.Challenges.DnsChallengeHelper.<CompleteDNSChallenge>d__4.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\Challenges\DNS\DnsChallengeHelper.cs:line 196

**Comment by webprofusion-chrisc** [comment]
Thanks I'll see if I can work it out from this and get back to you.

**Comment by webprofusion-chrisc** [comment]
Which version of SimpleDNS are you using? I'm currently investigating with v8 and I'm having to change stuff to get things working, which is odd.

**Comment by webprofusion-chrisc** [comment]
Hi, here is a test version of the SimpleDNS plugin to try:
https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/test/Plugin.DNS.SimpleDNSPlus.zip

You can extract that then copy the files into C:\ProgramFiles\Certify\Plugins to overwrite the existing SimpleDNS plugin, then restart the Certify service and relaunch the UI.

**Comment by posixx** [comment]
Yes it works now with this testversion. I'm using v8 indeed. The part which isn't working is the deletion of the TXT record even though the logifle says so. But this is also a problem of the v4.1.8 version; these TXT records aren't cleaned up at all..

**Comment by webprofusion-chrisc** [comment]
Thanks I'll see if I can fix that while I'm looking at it. I'm guessing you previously used an older version of SimpleDNS as otherwise I can't see how it would have worked (the API response just doesn't have the fields we were originally looking for).
