### ISSUE TITLE
Unexplained Crash

### ISSUE THREAD

**Issue by powertoaster** [webprofusion/certify#522]
Not really sure what this was caused by but thought I would give you a chance to review.

Application: LetsEncryptron.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at LetsEncryptron.IPTools.CloudFlareIPLookupHelper.Create(ILogger logger)
   at LetsEncryptron.Program.Main(String[] args)
   at LetsEncryptron.Program.<Main>(String[] args)

Faulting application name: LetsEncryptron.exe, version: 1.0.0.0, time stamp: 0x5e597f86
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1369, time stamp: 0x0a4b1e8e
Exception code: 0xe0434352
Fault offset: 0x0000000000039689
Faulting process id: 0x834
Faulting application start time: 0x01d677fbb2530713
Faulting application path: C:\Program Files\LetsEncryptron\LetsEncryptron.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f3783092-d3b1-4988-bbb1-ba95de77e373
Faulting package full name: 
Faulting package-relative application ID:

**Comment by webprofusion-chrisc** [comment]
Hi Wayne, happy to try and help but what is this? Is LetsEncryptron your own app?
