### ISSUE TITLE
Issues with deploying to an ADFS server

### ISSUE THREAD

**Issue by rickripe** [webprofusion/certify#524]
Certify/5.1.3.0 (Windows; Microsoft Windows NT 10.0.17763.0) 

When we deploy to the ADFS server we see this in the log:

2020-09-03 08:07:43.782 +10:00 [INF] Task [Deploy Certificate to ADFS] :: Task is enabled and primary request was successful.
2020-09-03 08:07:44.010 +10:00 [ERR] Deploy Certificate to ADFS (Deploy Certificate to ADFS) :: Task Failed with Exception :: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Plugin.DeploymentTasks.Shared.Helpers.ReadStringResource(String name)
   at Certify.Providers.DeploymentTasks.Adfs.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.DeploymentTask.<Execute>d__10.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\DeploymentTasks\DeploymentTask.cs:line 43
2020-09-03 08:07:44.010 +10:00 [INF] Deploy Certificate to ADFS :: Deploy Certificate to ADFS (Deploy Certificate to ADFS) :: Task Failed with Exception :: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Plugin.DeploymentTasks.Shared.Helpers.ReadStringResource(String name)
   at Certify.Providers.DeploymentTasks.Adfs.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DeploymentTasks.DeploymentTask.<Execute>d__10.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\DeploymentTasks\DeploymentTask.cs:line 43
2020-09-03 08:07:44.011 +10:00 [INF] Deployment Tasks did not complete successfully.

**Comment by webprofusion-chrisc** [comment]
Thanks Rick, a typo crept into the adfs task, it will be fixed in the next release. This implies that you have the honor of being the first one to try to use this task recently. In the meantime can you download the following update and try running the ADFS task again. I don't have an ADFS install to test with currently.

https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/test/Plugin.DeploymentTasks.Core.zip

You should extract this DLL and copy it over the existing one under C:\Program Files\CertifyTheWeb\Plugins\ then restart the Certify background service and relaunch the UI. 

Behind the scenes it will run the following script:
```ps
param($result, [switch] $restartServices = $false)
            
# https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap

Set-AdfsCertificate -CertificateType Service-Communications -Thumbprint $result.ManagedItem.CertificateThumbprintHash

Set-AdfsSslCertificate -Thumbprint $result.ManagedItem.CertificateThumbprintHash

# primary AD FS with Alternate TLS binding
# Set-AdfsAlternateTlsClientBinding -Thumbprint $result.ManagedItem.CertificateThumbprintHash

if ( $restartServices -eq $true) {

    Restart-Service WinHttpAutoProxySvc
    Restart-Service W3SVC
    Restart-Service adfssrv
}
```

**Comment by rickripe** [comment]
Fantastic – thanks Christopher.

Still issues though (and the same result after a restart of the server):

2020-09-03 11:21:15.727 +10:00 [INF] ---- Beginning Request [Default Web Site] ----
2020-09-03 11:21:15.740 +10:00 [INF] Certify/5.1.3.0 (Windows; Microsoft Windows NT 10.0.17763.0)
2020-09-03 11:21:16.112 +10:00 [INF] Beginning Certificate Request Process: Default Web Site using ACME Provider:Certes
2020-09-03 11:21:16.112 +10:00 [INF] Requested domains to include on certificate: adfs.pericorp.com
2020-09-03 11:21:16.121 +10:00 [INF] Beginning certificate order for requested domains
2020-09-03 11:21:16.146 +10:00 [INF] BeginCertificateOrder: creating/retrieving order. Retries remaining:2
2020-09-03 11:21:19.236 +10:00 [INF] Created ACME Order: https://acme-v02.api.letsencrypt.org/acme/order/65413585/4993550491
2020-09-03 11:21:19.624 +10:00 [INF] Fetching Authorizations.
2020-09-03 11:21:21.932 +10:00 [INF] Got http-01 challenge https://acme-v02.api.letsencrypt.org/acme/chall-v3/6925709431/vWfKSQ
2020-09-03 11:21:22.311 +10:00 [INF] Order authorizations already completed.
2020-09-03 11:21:22.340 +10:00 [INF] Requesting Certificate via Certificate Authority
2020-09-03 11:21:28.338 +10:00 [INF] Completed Certificate Request.
2020-09-03 11:21:28.461 +10:00 [INF] Performing Automated Certificate Binding
2020-09-03 11:21:29.872 +10:00 [INF] Completed certificate request and automated bindings update (IIS)
2020-09-03 11:21:29.956 +10:00 [INF] Request completed
2020-09-03 11:21:29.964 +10:00 [INF] Performing Post-Request (Deployment) Tasks..
2020-09-03 11:21:29.995 +10:00 [INF] Task: Deploy Certificate to ADFS :: Cannot create task provider for deployment task: System.ArgumentException: Deploy Task Type Unknown:certify.providers.deploymenttasks.adfs
   at Certify.Core.Management.DeploymentTasks.DeploymentTaskProviderFactory.Create(String taskTypeId, List`1 providerPlugins) in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\DeploymentTasks\DeploymentTaskProviderFactory.cs:line 101
   at Certify.Management.CertifyManager.<PerformTaskList>d__85.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\CertifyManager\CertifyManager.DeploymentTasks.cs:line 110
2020-09-03 11:21:29.996 +10:00 [INF] Deployment Tasks did not complete successfully.

Rick.

**Comment by webprofusion-chrisc** [comment]
Hi Rick, that looks a lot like the plugin didn't load, can you confirm your Plugins folder looks exactly like this. Note the Plugin.DeploymentTasks.Core.dll file should be there:

![image](https://user-images.githubusercontent.com/2445502/92061675-72e45f00-edc9-11ea-9cac-d1d05fa3e6a8.png)

**Comment by rickripe** [comment]
Looks very similar – but the supplied DLL does not have the same size:

[cid:image003.jpg@01D681E8.227BE8F0]

What was supplied:
[cid:image004.jpg@01D681E8.227BE8F0]

So, you look like you have a later version of that DLL.

NOTE I have added in the File Version – the file I copied across has version 1.0.0.0 (which is a bit odd as it doesn’t really reflect that it has been updated).  NOTE also that the dates are in UK format (not US format).

**Comment by webprofusion-chrisc** [comment]
Thanks your images didn't come through via email unfortunately. The File version is 1.0 because it's not built using the normal release build process which populates the version. 

No worries, I'll get a proper 5.1.4 release out very soon and you can try updating to that instead when you next get the chance. I'll check to see if I can get a basic ADFS install to test with as well.

**Comment by rickripe** [comment]
No dramas.  We have 89 days to get it installed and working 😊

**Comment by webprofusion-chrisc** [comment]
This fix (works for me on server 2019) has been included in v5.1.5, delete your existing ADFS task and create a new one just to be sure.

**Comment by rickripe** [comment]
I hit the rate limit ☹.  Will try again later on in the week.

**Comment by webprofusion-chrisc** [comment]
Thanks, I think you can just hit the Play button next to the Task if you've previously managed to get past the point where you request a certificate and it was just stopping on the ADFS Task, but yes you could just wait (if it's a test system you can add a additional test.domain.com hostname into the cert and it'll be seen as a new order).

**Comment by rickripe** [comment]
It’s production so I need to be careful about changes to the configuration.  Waiting is fine.  Thanks for the assistance.
