### ISSUE TITLE
RDP Gateway reployment error

### ISSUE THREAD

**Issue by marcovanbeek** [webprofusion/certify#532]
HI,

Just rolled out Certify The Web to a brand new Server 2019, and am getting the following error when deploying to the RDP Gateway:
2020-10-05 07:28:05.943 +00:00 [INF] Executing command via PowerShell
2020-10-05 07:28:06.156 +00:00 [ERR] Error - ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find drive. A drive with the name 'RDS' does not exist.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Certify.Management.PowerShellManager.InvokePowershell(CertificateRequestResult result, String executionPolicy, String scriptFile, Dictionary`2 parameters, String scriptContent, PowerShell shell, Boolean autoConvertBoolean) in C:\Work\GIT\certify_dev\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 206
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 100
 
I have had a brief look at the underlying script and one thing that I noticed is that it calls "Import-Module RemoteDesktopServices" which doesn't seem to be valid any more. As far as I can tell, this whole methodology no longer works and MS want all of this stuff done via a deployment. Which is annoying when all I want is a good old-fashioned gateway

**Comment by webprofusion-chrisc** [comment]
Thanks, I'll take a look at that. Meanwhile you should just provide your own script using the PowerShell script Task: https://docs.certifytheweb.com/docs/script-hooks

**Comment by webprofusion-chrisc** [comment]
Closing. This appears to be configuration-specific.
