### ISSUE TITLE
Error Running Script

### ISSUE THREAD

**Issue by BenjaminCsti** [webprofusion/certify#538]
Hello,

my certificate can't be renew because i have an error  :

(Use Custom Script) :: Error Running Script: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Certify.Core.Management.Challenges.DNS.DnsProviderScripting.<RunScript>d__26.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\Challenges\DNS\DnsProviderScripting.cs:line 169
Error: System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at Certify.Core.Management.Challenges.DNS.DnsProviderScripting.<RunScript>d__26.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Core\Management\Challenges\DNS\DnsProviderScripting.cs:line 182

Someone have already have this issue ?

Regards,

Benjamin

**Comment by webprofusion-chrisc** [comment]
Hi, nobody else has reported this issue, can you check that nothing has changed with your script or the things it runs.

If the problem persists please provide your script here as an example.

**Comment by BenjaminCsti** [comment]
Hi,ok i had an error on a path in the script .....
It's working now.

Thank you
