### ISSUE TITLE
Azure DNS doesn't support Azure Government

### ISSUE THREAD

**Issue by sramert-kbr** [webprofusion/certify#553]
I'm trying to use Certify in a government project that uses Azure US Government. However, it appears that the Azure DNS module doesn't support logging in to other Azure environments (e.g. "AzureUSGovernment", "AzureGermanCloud", etc.) Can this module be updated, please, to allow the use of other Azure environments?

**Comment by webprofusion-chrisc** [comment]
HI, thanks for suggesting this - this is (surprisingly!)  the first time this has been asked for. I'll check out what's required to make this  happen.

**Comment by webprofusion-chrisc** [comment]
Update: An enhancement has been developed and will be included in the next release. Let me know you want to test that in advance.

**Comment by sramert-kbr** [comment]
I'd be happy to test that for you! Please advise how to get the updated file(s).

Thanks for the quick fix! :)

**Comment by webprofusion-chrisc** [comment]
Great, so there is a test version of our Azue DNS plugin here: https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/test/Plugin.DNS.Azure.zip

You would download that and extract the `Plugin.DNS.Azure.dll` file and copy it over the existing file at `C:\Program Files\CertifyTheWeb\Plugins` then restart the Certify background service and re-open the UI. When you then add or replace Azure DNS credentials there should be a new 'Service' dropdown with a list of azure zones and you can choose `Azure US Government`.

**Comment by sramert-kbr** [comment]
Chris --

I installed the updated DLL as per your directions. However, I'm still not able to authenticate against Azure US Government.

When going through the setup process on the Authorization Settings screen, the domain does not get populated after configuring my credentials. (See attached screenshot)
![2021-04-08_9-23-02](https://user-images.githubusercontent.com/81712506/114044000-6a1aa680-984c-11eb-849e-12699935cc8d.png)

Likewise, if I try manually filling in the DNS Zone Name then clicking the "Test" button, I get the following error:

> DNS Challenge API Provider could not be created. Check all required credentials are set. Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS900382: Confidential Client is not supported in Cross Cloud request.
Trace ID: 7765f5e1-9c50-46c7-b110-9543a3d25101
Correlation ID: 0dc2cbfd-41eb-4cef-9dc4-51e8126ebb59
Timestamp: 2021-04-08 14:09:13Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: 7765f5e1-9c50-46c7-b110-9543a3d25101\r\nCorrelation ID: 0dc2cbfd-41eb-4cef-9dc4-51e8126ebb59\r\nTimestamp: 2021-04-08 14:09:13Z","error_codes":[900382],"timestamp":"2021-04-08 14:09:13Z","trace_id":"7765f5e1-9c50-46c7-b110-9543a3d25101","correlation_id":"0dc2cbfd-41eb-4cef-9dc4-51e8126ebb59"}: Unknown error
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.Internal.MemoryApplicationAuthenticationProvider.<AuthenticateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Certify.Providers.DNS.Azure.DnsProviderAzure.<InitProvider>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Core.Management.Challenges.ChallengeProviders.<GetDnsProvider>d__2.MoveNext() in D:\a\certify-service\certify-service\src\certify-build\certify\src\Certify.Core\Management\Challenges\ChallengeProviders.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Core.Management.Challenges.DnsChallengeHelper.<CompleteDNSChallenge>d__4.MoveNext() in D:\a\certify-service\certify-service\src\certify-build\certify\src\Certify.Core\Management\Challenges\DNS\DnsChallengeHelper.cs:line 137
	ErrorCode: invalid_request
	StatusCode: 400

My guess, without seeing the source code, is that your code is referencing hard-coded REST API endpoints for Azure Public. Unfortunately, with Azure US Government, there's different REST API endpoints. (I couldn't say for sure if the same holds true for other Azure environments like Azure China or Azure Germany.) This link should help with providing those endpoints: https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#guidance-for-developers
Specifically, the endpoints you'll probably need are "management.usgovcloudapi.net" and "login.microsoftonline.us". The former is the actual REST API endpoint and the latter is the Azure US Government Azure Active Directory tenant login URL. 

Let me know if you have any questions or can provide you with additional information.

Thanks for your work on this Chris!

**Comment by webprofusion-chrisc** [comment]
Thanks for testing, sorry I missed your reply. Unfortunately there's just no way for me to develop and test this any further with the type of Azure access that I have. Our source code is here and pull requests are welcome :)
https://github.com/webprofusion/certify/blob/development/src/Certify.Providers/DNS/Azure/DnsProviderAzure.cs#L94

Note that it is possible to build the Azure DNS provider and drop the .dll into C:\Program Files\CertifyTheWeb\Plugins then restart the Certify service and UI.

**Comment by webprofusion-chrisc** [comment]
A fix for this will be included in the next update. I can't fully test it from my side (I only have access to Azure global) but I can confirm that the respective Azure AD management URLs etc are updated this time.
