### ISSUE TITLE
DNSimple (possibly other Posh-ACME modules) do not run unless execution policy is set to unrestricted

### ISSUE THREAD

**Issue by thx1200** [webprofusion/certify#557]
### Summary
Our corporate domain uses GPO to ensure execution policy for PowerShell is always set to RemoteSigned.  This causes the DNSimple module (possibly all Posh-ACME modules) to fail to run with an execution policy exception.  This shouldn't be the case because all scripts are stored in Program Files, so are considered by Windows as local scripts.  As such, the execution policy RemoteSigned is compatible with script execution for CertifyTheWeb.  It seems that the PowerShell execution via the runspace may be explicitly requesting Unrestricted level of access when it is not needed, which would be requiring a less secure runtime environment unnecessarily.  In either case, can you update the code to have an option to explicitly not attempt to update execution policy?  If it fails, then it fails, but at least it won't fail before even trying.

### More about execution policies
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1

### Error returned from CertifyTheWeb
Powershell/PoshACME DNS :: Error - CmdletInvocationException: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.Management.PowerShellManager.InvokePowershell(CertificateRequestResult result, **String executionPolicy**, String scriptFile, Dictionary`2 parameters, String scriptContent, PowerShell shell, Boolean autoConvertBoolean, String[] ignoredCommandExceptions) in D:\a\certify-service\certify-service\src\certify-build\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 148
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in D:\a\certify-service\certify-service\src\certify-build\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 122

**Comment by thx1200** [comment]
I think I found the code.  "Unrestricted" appears to be the default value for the execution policy.  https://github.com/webprofusion/certify/blob/7deb090263b63b50a149dcaa7d00047efd7af119/src/Certify.Core/Management/Challenges/DNS/DnsProviderPoshACME.cs#L110

**Comment by webprofusion-chrisc** [comment]
Hi, you can change the default execution policy by editing `C:\ProgramData\Certify\serviceconfig.json` and using a blank string to apply your default policy:

https://docs.certifytheweb.com/docs/script-hooks/#troubleshooting

You then need to restart the Certify background service and re-launch the UI. From there you should be bale to use the 'test' button on any managed certificate that uses the same provider to verify that the script is running ok.

**Comment by thx1200** [comment]
Ah thank you that did the trick.  I still think the default setting shouldn't be so permissive, that's not good practice for PowerShell.  But this resolves my immediate need.

**Comment by webprofusion-chrisc** [comment]
Thanks, I don't disagree from a security perspective. For us it's a balance of usability (and predictable behavior) vs security and there are many other similar discussions to be had. We possibly need an option in the installer to opt for an overall hardened mode (with a link to how to fix all the common permissions problems you'll experience as a result). 

We do basically default everything to 'easy mode' regarding permissions as a _very_ significant portion of our user base are not experienced administrators, however we need to cater more for those who are prepared to do the extra work to test and debug their configuration with tighter permissions in place.

**Comment by thx1200** [comment]
Thanks for the explanation and consideration!  I like the idea of a more general "hardened mode."
