### ISSUE TITLE
Running certify list --json with no file path causes crash

### ISSUE THREAD

**Issue by JohnDuprey** [webprofusion/certify#566]
Version 5.5.2.0

This is the output that is received when running certify list --json with no file:

```
Certify SSL Manager - CLI Certify.Core v5.5.2.0
For more information see https://certifytheweb.com

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Certify.CLI.CertifyCLI.ListManagedCertificates(String[] args) in D:\a\certify-service\certify-service\src\certify-
build\certify\src\Certify.CLI\CertifyCLI.cs:line 253
   at Certify.CLI.Program.<Main>d__1.MoveNext() in D:\a\certify-service\certify-service\src\certify-build\certify\src\Ce
rtify.CLI\Program.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.CLI.Program.<Main>(String[] args)
```

**Comment by webprofusion-chrisc** [comment]
Thanks John! This will be fixed in the next update.
