### ISSUE TITLE
DNS problem: query timed out looking up MX for

### ISSUE THREAD

**Issue by Napsterbater** [webprofusion/Certify#6]
Trying out your client, very excited for a Windows based ACME client.

I'm having an issue even getting started though. 

This is with version 0.9.85 alpha 10

`
[10:21 PM] Powershell: Initialize-ACMEVault -BaseURI https://acme-v01.api.letsencrypt.org/
[10:21 PM] Powershell: New-ACMERegistration -Contacts mailto:bjackson@napshome.net
[10:21 PM] [Error]: System.Management.Automation.CmdletInvocationException: DNS problem: query timed out looking up MX for napshome.net ---> ACMESharp.AcmeClient+AcmeWebException: Unexpected error
 +Response from server:
	+ Code: BadRequest
	+ Content: {"type":"urn:acme:error:invalidEmail","detail":"DNS problem: query timed out looking up MX for napshome.net"} ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message)
   --- End of inner exception stack trace ---
   at ACMESharp.AcmeClient.Register(String[] contacts)
   at ACMESharp.POSH.NewRegistration.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.InvokeCurrentPSCommand()
[10:21 PM] Powershell: Update-ACMERegistration -AcceptTOS
[10:21 PM] [Error]: System.Management.Automation.CmdletInvocationException: No registrations found ---> System.InvalidOperationException: No registrations found
   at ACMESharp.POSH.UpdateRegistration.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.PowershellManager.InvokeCurrentPSCommand()
`

**Comment by webprofusion-chrisc** [comment]
Hi, you'll need to provide a valid email address as your contact (the error said it couldn't identify the mail exchange dns details). This is a requirement of the Lets Encrypt service, not certify specifically. Try deleting your vault folder and starting again with a valid email address?

**Comment by Napsterbater** [comment]
It is a valid e-mail. domain is valid. That the problem.

It can be confirmed here http://mxtoolbox.com/SuperTool.aspx?action=mx%3anapshome.net&run=toolpage

**Comment by Napsterbater** [comment]
Seems it was an issue with Letsencrypt's DNS servers, tried it again today, all better.
