### ISSUE TITLE
DNS Validation Fails for IONOS DNS API

### ISSUE THREAD

**Issue by eneerge** [webprofusion/certify#635]
When attempting to use dns validation with IONOS (IONOS DNS API), an error occurs.

This is with version 6.0.2. Version 5.9.2 works fine. I uninstalled 6.0.2 and installed 5.9.2 and it worked fine without even recreating the IONOS credentials.

> Failed [IONOS DNS API]: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type '<>f__AnonymousType0`4[System.String,System.String,System.String,<>f__AnonymousType1`8[System.String,System.String,System.String,System.String,System.String,System.String,System.Int32,System.Boolean][]]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Certify.Providers.DNS.IONOS.DnsProviderIONOS.<GetRecordsForZone>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Providers.DNS.IONOS.DnsProviderIONOS.<CreateRecord>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certify.Core.Management.Challenges.DnsChallengeHelper.<CompleteDNSChallenge>d__4.MoveNext() in D:\a\certify-internal\certify-internal\src\certify-build\certify\src\Certify.Core\Management\Challenges\DNS\DnsChallengeHelper.cs:line 189

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue, could you try the latest v6.0.4 on a test machine (it can just be a desktop)? Some 6.x versions prior to that had problems with outdated DLLs. If the problem persists I can get you a test plugin to try.

**Comment by webprofusion-chrisc** [comment]
Please re=open this issue if it's still a problem.
